// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bert.proxies;

public class KBPredictResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kBPredictResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BERT.KBPredictResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KBEmbeddingString("KBEmbeddingString");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KBPredictResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KBPredictResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kBPredictResponseMendixObject)
	{
		if (kBPredictResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, kBPredictResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.kBPredictResponseMendixObject = kBPredictResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static bert.proxies.KBPredictResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bert.proxies.KBPredictResponse(context, mendixObject);
	}

	public static bert.proxies.KBPredictResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bert.proxies.KBPredictResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of KBEmbeddingString
	 */
	public final java.lang.String getKBEmbeddingString()
	{
		return getKBEmbeddingString(getContext());
	}

	/**
	 * @param context
	 * @return value of KBEmbeddingString
	 */
	public final java.lang.String getKBEmbeddingString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KBEmbeddingString.toString());
	}

	/**
	 * Set value of KBEmbeddingString
	 * @param kbembeddingstring
	 */
	public final void setKBEmbeddingString(java.lang.String kbembeddingstring)
	{
		setKBEmbeddingString(getContext(), kbembeddingstring);
	}

	/**
	 * Set value of KBEmbeddingString
	 * @param context
	 * @param kbembeddingstring
	 */
	public final void setKBEmbeddingString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kbembeddingstring)
	{
		getMendixObject().setValue(context, MemberNames.KBEmbeddingString.toString(), kbembeddingstring);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kBPredictResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bert.proxies.KBPredictResponse that = (bert.proxies.KBPredictResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
