// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bert.proxies;

public class ML_Output_Entity_Single_sequence_tokenizer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mL_Output_Entity_Single_sequence_tokenizerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BERT.ML_Output_Entity_Single_sequence_tokenizer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Last_hidden_state("Last_hidden_state");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ML_Output_Entity_Single_sequence_tokenizer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ML_Output_Entity_Single_sequence_tokenizer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mL_Output_Entity_Single_sequence_tokenizerMendixObject)
	{
		if (mL_Output_Entity_Single_sequence_tokenizerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mL_Output_Entity_Single_sequence_tokenizerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mL_Output_Entity_Single_sequence_tokenizerMendixObject = mL_Output_Entity_Single_sequence_tokenizerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static bert.proxies.ML_Output_Entity_Single_sequence_tokenizer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new bert.proxies.ML_Output_Entity_Single_sequence_tokenizer(context, mendixObject);
	}

	public static bert.proxies.ML_Output_Entity_Single_sequence_tokenizer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return bert.proxies.ML_Output_Entity_Single_sequence_tokenizer.initialize(context, mendixObject);
	}

	/**
	 * @return value of Last_hidden_state
	 */
	public final java.lang.String getLast_hidden_state()
	{
		return getLast_hidden_state(getContext());
	}

	/**
	 * @param context
	 * @return value of Last_hidden_state
	 */
	public final java.lang.String getLast_hidden_state(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Last_hidden_state.toString());
	}

	/**
	 * Set value of Last_hidden_state
	 * @param last_hidden_state
	 */
	public final void setLast_hidden_state(java.lang.String last_hidden_state)
	{
		setLast_hidden_state(getContext(), last_hidden_state);
	}

	/**
	 * Set value of Last_hidden_state
	 * @param context
	 * @param last_hidden_state
	 */
	public final void setLast_hidden_state(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String last_hidden_state)
	{
		getMendixObject().setValue(context, MemberNames.Last_hidden_state.toString(), last_hidden_state);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mL_Output_Entity_Single_sequence_tokenizerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bert.proxies.ML_Output_Entity_Single_sequence_tokenizer that = (bert.proxies.ML_Output_Entity_Single_sequence_tokenizer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
