// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package bert.actions;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.mlkit.MLKit;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Base64;
import java.nio.charset.StandardCharsets;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.LongBuffer;
import java.util.HashMap; // Make sure this import is at the top of your file
import java.util.Arrays;
import java.nio.ByteOrder;

public class User_question_post_processor extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use OutputEntity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OutputEntity;
	private final bert.proxies.ML_Output_Entity_Single_sequence_tokenizer OutputEntity;

	public User_question_post_processor(
		IContext context,
		IMendixObject _outputEntity
	)
	{
		super(context);
		this.__OutputEntity = _outputEntity;
		this.OutputEntity = _outputEntity == null ? null : bert.proxies.ML_Output_Entity_Single_sequence_tokenizer.initialize(getContext(), _outputEntity);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		final IMendixObject outputObject = Core.instantiate(getContext(), "BERT.PredictResponse");
		outputObject.setValue(getContext(), "EmbeddingString", "");

		return outputObject;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "User_question_post_processor";
	}

	// BEGIN EXTRA CODE
	private static final int MAX_ANS_LEN = 30;
	private static final int PREDICT_ANS_NUM = 5;
	private static final int OUTPUT_OFFSET = 1;
	private static final int MAX_SEQ_LEN = 32;
	final int SEQUENCE_LENGTH = 32;
	final int FEATURE_SIZE = 768;

	// END EXTRA CODE
}
