// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package bert.actions;

import com.mendix.core.Core;
import com.mendix.mlkit.MLKit;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.InputStream;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.Arrays;
import java.util.Base64;

public class User_question_pre_processor extends CustomJavaAction<IMendixObject>
{
	public User_question_pre_processor(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

        long[][] inputMask = new long[1][MAX_SEQ_LEN];
        long[][] inputIds = new long[1][MAX_SEQ_LEN];
        long[][] tokenTypeIds = new long[1][MAX_SEQ_LEN];

        for (int j = 0; j < MAX_SEQ_LEN; j++) {
            if (j < 32) {
                inputMask[0][j] = 0;
                inputIds[0][j] = 0;
                tokenTypeIds[0][j] = 0;
            } else {
                inputMask[0][j] = 0;
                inputIds[0][j] = 0;
                tokenTypeIds[0][j] = 0;
            }
        }
        InputStream inputIdsIs = MLKit.toInputStream(inputIds);
        InputStream inputMaskIs = MLKit.toInputStream(inputMask);
        InputStream tokenTypeIdsIs = MLKit.toInputStream(tokenTypeIds);

        final IMendixObject outputObject = Core.instantiate(getContext(), "BERT.ML_Input_Entity_Single_sequence_tokenizer");

        outputObject.setValue(getContext(), "Attention_mask", MLKit.toBase64(inputMaskIs));
        outputObject.setValue(getContext(), "Input_ids", MLKit.toBase64(inputIdsIs));
        outputObject.setValue(getContext(), "Token_type_ids", MLKit.toBase64(tokenTypeIdsIs));


        return outputObject;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "User_question_pre_processor";
	}

	// BEGIN EXTRA CODE
    private static final boolean DO_LOWER_CASE = true;
    private static final int MAX_SEQ_LEN = 32;
	// END EXTRA CODE
}
