// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bert.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the BERT module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_CallModelsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BERT.SUB_CallModels");
		return builder;
	}

	public static void sUB_CallModels(IContext context)
	{
		sUB_CallModelsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Vectorize_KnowledgebaseBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BERT.SUB_Vectorize_Knowledgebase");
		return builder;
	}

	public static void sUB_Vectorize_Knowledgebase(IContext context)
	{
		sUB_Vectorize_KnowledgebaseBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Vectorize_User_QuestionBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("BERT.SUB_Vectorize_User_Question");
		return builder;
	}

	public static void sUB_Vectorize_User_Question(IContext context)
	{
		sUB_Vectorize_User_QuestionBuilder().execute(context);
	}
}
